### ISSUE TITLE
[Feature Request] `conda-forge`-hosted Anaconda package

### ISSUE THREAD

**Issue by leycec** [beartype/pytest-beartype#4]
Hi, @tusharsadhwani! I'm *baaaaaaaack.* It's like a horror movie – only less unsettling and more awkward.

I have a new feature request, which you are (of course) welcome to ignore or refuse. I just realized, though... an Anaconda package for `pytest-beartype` would be the chef's kiss. Do you have any experience with `conda-forge`? If not, wonderful! This is your lucky Thursday. @beartype offers many novel experiences, including joining `conda-forge` and submitting your first `conda-forge` package. Excitement! Thrills! Code!

Let me know if you'd like any assistance here. I currently maintain [@beartype's official `conda-forge` feedstack](https://github.com/conda-forge/beartype-feedstock). This is a bureaucratic workflow I know all too much about. If this is your first time around the bend, here's my **tl;dr**:

1. Follow the [**official instructions** at the `conda-forge/staged-recipes` repo](https://github.com/conda-forge/staged-recipes?tab=readme-ov-file#getting-started). Pretty simple stuff, really. Fork the repo *blah blah.* Boring!
1. Create a new `conda-forge` recipe for `pytest-beartype` in your `staged-recipes` fork. The easiest ways are probably to either:
   * Copy-and-paste [@beartype's official `conda-forge` recipe](https://github.com/conda-forge/beartype-feedstock/blob/main/recipe/meta.yaml) into your `staged-recipes` fork. Hack on it a ~~lot~~ little bit. Viola! Recipe hopefully works.
   * Use [**Greyskull**](https://github.com/conda-forge/staged-recipes?tab=readme-ov-file#grayskull---recipe-generator-for-python-packages-on-pypi) to auto-generate a `pytest-beartype` recipe from your existing PyPI package. Never tried this, honestly – but it's bound to magically work great, right? Devtooling is fun. :yum: 

Oh – and thanks again for all your sumptuous efforts here. You are the hero of QA.

**Comment by tusharsadhwani** [comment]
Sounds legit. I'll hack on this, perhaps on the weekend, since I'm traveling back home as of now.

**Comment by leycec** [comment]
**Legit.** Gods, how I've missed hearing that word. Sounds great! Take your time. No rush whatsoever. It's all fun and hacking, here. Oh – and have a great trip, especially if you're travelling by train...

Gods, how I miss trains. Riding the [Shinkansen (bullet train) in Japan](https://en.wikipedia.org/wiki/Shinkansen) was a peak experience I shall always treasure. :bullettrain_front: :train: :dash:

**Comment by tusharsadhwani** [comment]
Oh yes, Shinkansen is nuts. I hear they're making an [even faster one](https://en.m.wikipedia.org/wiki/Ch%C5%AB%C5%8D_Shinkansen) to go between Tokyo and Osaka in about an hour.

**Comment by leycec** [comment]
**Oh. Oh. Oh.** As if Japan couldn't get any more peak. Someday, Canada may catch up to where Japan was in the 60's. I cry while laughing. :rofl: 

Hope you had a great trip! Bengaluru looks *so* gorgeous. I had no idea. I'm genuinely shocked. I'm a huge sucker for botanical gardens. They're literally everywhere in that city. It's like one big giant sprawling garden where people incidentally live. Props for choosing Teh Coolest City Evah.

**Comment by tusharsadhwani** [comment]
Bangalore would be pretty cool if most of the lakes were kept clean (they often reek especially during rain season) and they was better public transport (it has the 2nd worst traffic times, just next to London).

I'm sure Indian megacities will get there in a decade or so. Gardens always greener on the other side kinda thing.

**Comment by tusharsadhwani** [comment]
I'm looking into [pixi](https://prefix.dev/), which is supposed to make the packaging and uploading to conda as seamless as something like poetry is for pip today. I think I'll give that a shot.

**Comment by tusharsadhwani** [comment]
I'll probably be going the smithy route, pixi seems much more to be a very helpful conda installation tool than a very helpful conda publishing tool. #5

**Comment by leycec** [comment]
**Gah!** I feel sorrow for not replying sooner. This summer has been a Canadian hothouse madhouse. Our fridge broke in a heatwave and now the freezer-burned scallops are all rotting in buckets. Uhm... I've said too much. What I *meant* to say was:

> "I recall `conda` being *super* easy. Just go the `conda-forge` route unless you hate yourself, in which case please carry on with Smithy. Actually, learning Smithy *could* be super-fun. No idea! Never bothered. But perhaps bothering is worthwhile if you're deep into the tooling side? Frankly, `conda-forge` is the only reason I published @beartype to `conda`. Without `conda-forge` automation (*...which I only barely and dimly comprehend*), `conda` would be too utterly painful to support.

`conda-forge`. `conda-forge` is what I'm saying while I sweat in this heatwave to the smell of rotting scallops. :joy: 

Specifically, either:

* Consider following [this **4-Step Plan**](https://github.com/conda-forge/staged-recipes#getting-started) to manually generate a new `conda-forge` hosted package. This is what I did. I don't need *yet another* automation toolchain like [Grayskull](https://github.com/conda-incubator/grayskull) in my open-source life. I've already got so many of those toolchains in my dev kit already that I can barely pick my dev kit up.
* Install [Grayskull](https://github.com/conda-incubator/grayskull) if you live dangerous, wild, and carefree.

Hope you're having an awesome summer in Bengaluru. Rotting smelly lakes sounds... not so great, admittedly. But it could be worse! Like, Bengaluru could be out of water entirely. Wait. Didn't that happen? Wait. How could Bengaluru be out of water when it's surrounded by rotting smelly lakes? Hmmmmmm. Ok. I get it. I wouldn't want to drink from a rotting smelly lake, either. :sweat:

**Comment by bollwyvl** [comment]
Thanks for this lovely package!

I've started https://github.com/conda-forge/staged-recipes/pull/28068.

Hopefully it will be reviewed, (maybe fixed, pass again, etc.) and then should be available on conda-forge shortly thereafter. 

Upstream maintainers are _certainly_ welcome to participate as maintainers: add a comment on that PR (or on an issue in the future `conda-forge/pytest-beartype-feedstock` to that effect) and you, too, can Press The Button when the bot makes PRs after new PyPI releases (usually in a few hours).

Of note: it would be lovely if the `tests` were shipped along with the `.tar.gz` on PyPI. This would be either a single line in `MANIFEST.in`, or a general `pyproject.toml` overhaul, either of which I'd be happy to PR, if desired.

Having (or even running) isn't a blocker to getting on conda-forge, as the recipe can pull the GitHub tarball (provided it continues to be tagged). However, having just one file/SHA does reduce packaging entropy: GitHub tarballs _have_ change their SHAs, while PyPI packages generally can't.

**Comment by tusharsadhwani** [comment]
I'll happily accept the changes, whatever is cleaner, to pyproject or manifest. Thanks for wrapping up the work on my behalf :D I'm truly grateful

**Comment by tusharsadhwani** [comment]
Can you clarify how I can posess the powers of The Button? what kind of comnent on that PR do I need to drop?

**Comment by bollwyvl** [comment]
> posess the powers of The Button

Make a comment on that PR to the effect of:

```
I, @tusharsadhwani, as the upstream maintainer of `pytest-beartype`, do solemnly swear
to share in the duties of conda-forge maintainership of this package.
```

or, more simply, _Please add me as a maintainer_

Then I'll add you to the `meta.yaml#about/maintainers` key, and lots of magic stuff will happen after the merge, resulting in an invitation to the `conda-forge` org. You'll start getting emails, and can make any needed non-bot PRs from a fork... just don't generally do anything directly on the future `pytest-beartype-feedstock` repo, as pretty much any commit will result in the machine trying to ship.

**Comment by tusharsadhwani** [comment]
I've released a patch release: `v0.1.1` to reflect the sdist changes.

**Comment by bollwyvl** [comment]
Now up, might be a few minutes before it's on all the CDN nodes:

https://anaconda.org/conda-forge/pytest-beartype/files?version=0.1.1

**Comment by bollwyvl** [comment]
(here's the new repo: https://github.com/conda-forge/pytest-beartype-feedstock)

**Comment by tusharsadhwani** [comment]
Awesome work!
I plan on releasing v0.2 soon enough with #9, hopefully the conda release will just go through, but if it doesn't I'll tag you here.

Thanks again 😄

**Comment by bollwyvl** [comment]
Yep. Good packaging metadata makes the bot happy, good luck on #9!

**Comment by bollwyvl** [comment]
You may see some emails about https://github.com/conda-forge/pytest-beartype-feedstock/pull/1 : this will just give us some better future PR messages when 0.2 lands. Feel free to review (and/or Press The Button), but will likely self-merge. As we have robust tests in place, we _could_ let that autoupdate and automerge, but I don't mind putting at least _one_ set of human eyeballs in the loop.

**Comment by tusharsadhwani** [comment]
Okay, v0.2 has been released a while, what do I do to get it on conda now? Do I manually bump the version in [meta.yaml](https://github.com/conda-forge/pytest-beartype-feedstock/blob/main/recipe/meta.yaml) here?

**Comment by bollwyvl** [comment]
Wow, cool. :tada: 

The bot takes a while, but you can juice it with an issue with the title `@conda-forge-admin please update version`. It'll start a draft, grab the versions, etc... but _won't_ complain about dep changes (if any).

Feel free to go for it, or i can hit it later!

**Comment by leycec** [comment]
**WOAH.** This issue went light-speed faster than a greased weasel through a jar of peanut-butter. Thanks so much to:

* @bollwyvl for forging this magical conduit between `pytest-beartype` and @conda-forge.
* @tusharsadhwani for graciously maintaining this mad package for nearly... *wait.* Has it really almost been a year?!? :face_holding_back_tears: 

![](https://media1.tenor.com/m/KVIwMFMvT9UAAAAd/speed-lightspeed.gif)
<sup>**Team Bear:** *Let's gooooo!*</sup>
