### ISSUE TITLE
[Feature Request] Beartype all the things

### ISSUE THREAD

**Issue by frrad** [beartype/pytest-beartype#6]
If I put `*` I would like to run beartype on all packages

**Comment by tusharsadhwani** [comment]
You know what, great idea. I'll have to dig a little bit into beartype for this but it is an important feature to have.

**Comment by tusharsadhwani** [comment]
I've released `v0.1.0`, if it doesn't work as intended please let me know.

**Comment by leycec** [comment]
:partying_face: 

**Thanks so much,** @tusharsadhwani. WOW!!! Just... *wow.* You're amazing. If only I had your release super-powers. If only I could just release @beartype 0.19.0 already. If only I wasn't a crippling perfectionist. If only I tried hard to be a little more like @tusharsadhwani. It's been *months* already. Oh, well. Time to pass out and try again tomorrow. :sleeping:
